name: Daily EMP Update

on:
  schedule:
    - cron: '0 14 * * *'   # 10:00 AM Bolivia time (UTC-4)
  workflow_dispatch:         # Allow manual trigger

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Set up Kaggle credentials
        run: |
          mkdir -p ~/.config/kaggle
          echo '{"username":"${{ secrets.KAGGLE_USERNAME }}","key":"${{ secrets.KAGGLE_KEY }}"}' > ~/.config/kaggle/kaggle.json
          chmod 600 ~/.config/kaggle/kaggle.json

      - name: Run EMP pipeline
        env:
          SUPABASE_URL:              ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: |
          python emp_pipeline.py --upload --out emp_output.csv

      - name: Export data.json for dashboard
        run: python export_json.py

      - name: Commit dashboard data
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/data.json docs/emp_daily.csv
          git diff --staged --quiet || git commit -m "chore: daily EMP update $(date -u +%Y-%m-%d)"
          git push
